deploy_path: /var/www/colinta
host: https://colinta.com
strip_metadata_from_name: true
strip_metadata_from_target_name: true
meta:
  analytics: 'UA-15076738-1'
  title: 'code by colinta'
  description: ''
author:
  name: Colin T.A. Gray
  email: colinta@gmail.com
  github: https://github.com/colinta
  twitter: colinta
filters:
  date: strange_case.extensions.date.date
  markdown: strange_case.extensions.misaka.markdown
  json: json.dumps
  sha: strange_case.extensions.hashlib.sha
  md5: strange_case.extensions.hashlib.md5
  pluralize: strange_case.extensions.inflect.pluralize
processors:
  - strange_case.extensions.image
  - strange_case.extensions.scss
ignore:
  - '.*'
  - config.yaml
